[phases.setup]
aptPkgs = ["python3-pip", "python3-dev", "build-essential", "libpq-dev"]

[phases.build]
commands = [
    "pip install --upgrade pip",
    "pip uninstall -y numpy pandas",
    "pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "python manage.py migrate && gunicorn kfp_reporting.wsgi:application --bind 0.0.0.0:$PORT"
