[phases.setup]
aptPkgs = ["python3-pip", "python3-dev", "build-essential", "libpq-dev"]

[phases.build]
commands = ["pip install -r requirements.txt", "python manage.py migrate", "python init_database.py"]

[start]
cmd = "python start_railway.py"
