[phases.setup]
aptPkgs = ["python3-pip", "python3-dev", "build-essential", "libpq-dev", "nodejs", "npm"]

[phases.build]
commands = [
    "pip install -r requirements.txt",
    "cd frontend && npm install && npm run build"
]

[start]
cmd = "python start_railway.py"
