# Generated by Django 4.2.7 on 2025-09-22 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название отчета')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('chart_type', models.CharField(max_length=50, verbose_name='Тип графика')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Шаблон отчета',
                'verbose_name_plural': 'Шаблоны отчетов',
            },
        ),
        migrations.CreateModel(
            name='AgriculturalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255, verbose_name='Поле')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('planting_area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Площадь посева (га)')),
                ('yield_per_hectare', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Урожайность (ц/га)')),
                ('crop', models.CharField(max_length=255, verbose_name='Культура')),
                ('variety', models.CharField(max_length=255, verbose_name='Сорт')),
                ('final_product', models.CharField(max_length=255, verbose_name='Конечный продукт')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Загружено пользователем')),
            ],
            options={
                'verbose_name': 'Сельскохозяйственные данные',
                'verbose_name_plural': 'Сельскохозяйственные данные',
                'ordering': ['-year', 'field_name', 'crop'],
                'unique_together': {('field_name', 'year', 'crop', 'variety')},
            },
        ),
    ]
