# Generated by Django 4.2.7 on 2025-09-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agriculturaldata',
            name='agro_background',
            field=models.CharField(blank=True, max_length=255, verbose_name='Агрофон'),
        ),
        migrations.AddField(
            model_name='agriculturaldata',
            name='brigade',
            field=models.CharField(blank=True, max_length=255, verbose_name='Бригада'),
        ),
        migrations.AddField(
            model_name='agriculturaldata',
            name='field_old_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Поле (старое название)'),
        ),
        migrations.AddField(
            model_name='agriculturaldata',
            name='gross_harvest',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Валовый сбор (тн)'),
        ),
        migrations.AddField(
            model_name='agriculturaldata',
            name='predecessor',
            field=models.CharField(blank=True, max_length=255, verbose_name='Предшественник'),
        ),
        migrations.AddField(
            model_name='agriculturaldata',
            name='productivity_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Балл продуктивности'),
        ),
        migrations.AddField(
            model_name='agriculturaldata',
            name='pzr',
            field=models.CharField(blank=True, max_length=255, verbose_name='ПЗР'),
        ),
        migrations.AddField(
            model_name='agriculturaldata',
            name='reproduction',
            field=models.CharField(blank=True, max_length=255, verbose_name='Репродукция'),
        ),
    ]
