# Generated by Django 4.2.7 on 2025-09-29 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_agriculturaldata_agro_background_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agriculturaldata',
            options={'ordering': ['-year', 'field_name', 'final_product'], 'verbose_name': 'Сельскохозяйственные данные', 'verbose_name_plural': 'Сельскохозяйственные данные'},
        ),
        migrations.AlterUniqueTogether(
            name='agriculturaldata',
            unique_together={('field_name', 'year', 'final_product', 'variety')},
        ),
    ]
