# Generated by Django 4.2.7 on 2025-10-12 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0003_alter_agriculturaldata_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agriculturaldata',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Загружено пользователем'),
        ),
    ]
